"""
Deterministic synthetic demo.

All documents here are clearly labelled synthetic and describe a
fictional patient. PDFs are generated byte-for-byte identically on
every run, so SHA-256 deduplication keeps the demo idempotent.
"""

from pathlib import Path

import pymupdf
from sqlalchemy.orm import Session

from .config import BACKEND_DIR
from .models import (
    Consent,
    Document,
    EvidenceToken,
    OutboundMessage,
    Transaction,
    WhatsAppMessage,
)


DEMO_DATA_DIR = BACKEND_DIR.parent / "data" / "demo"

SYNTHETIC_BANNER = (
    "SYNTHETIC DEMO DOCUMENT - NOT REAL PATIENT DATA"
)

PRESCRIPTION = "jeevaflow_demo_prescription_2026-09-20.pdf"
INITIAL_REPORT = "jeevaflow_demo_lab_report_2026-06-15.pdf"
FOLLOWUP_REPORT = "jeevaflow_demo_followup_hba1c_2026-09-20.pdf"
CONFLICT_REPORT = "jeevaflow_demo_lab_copy_2026-06-15.pdf"
FOLLOWTHROUGH_PLAN = "jeevaflow_demo_followthrough_plan_2026-10-05.pdf"
FOLLOWTHROUGH_LABS = "jeevaflow_demo_followthrough_labs_2026-12-28.pdf"


DEMO_DOCUMENTS = {
    PRESCRIPTION: f"""{SYNTHETIC_BANNER}

JEEVAFLOW DEMO CLINIC - PRESCRIPTION

Dr. Example Physician
Reg. No: SYN-12345
Date: 20/09/2026

Patient: JeevaFlow Demo Patient

Allergies: Penicillin (rash)

Rx
1. Tab Metformin 500 mg 1-0-1 x 30 days
2. Tab Atorvastatin 10 mg once daily at night for 30 days
3. Tab Glimepiride 1 mg
4. Tab Zyxorin 50 mg BD x 5 days

Advice
Repeat HbA1c after 3 months.
Review in 4 weeks.
""",
    INITIAL_REPORT: f"""{SYNTHETIC_BANNER}

JEEVAFLOW DEMO MEDICAL REPORT

Patient: JeevaFlow Demo Patient
Report Date: 15/06/2026

Laboratory Results

HbA1c: 9.4 %
Glucose: 186 mg/dL

Doctor Instructions

Repeat HbA1c after 3 months.
Follow-up with physician.
Review laboratory results at follow-up.
""",
    FOLLOWUP_REPORT: f"""{SYNTHETIC_BANNER}

JEEVAFLOW DEMO LABORATORY RESULT

Patient: JeevaFlow Demo Patient
Report Date: 20/09/2026

Laboratory Results

HbA1c: 8.1 %
""",
    CONFLICT_REPORT: f"""{SYNTHETIC_BANNER}

JEEVAFLOW DEMO LABORATORY RESULT (TRANSCRIBED COPY)

Patient: JeevaFlow Demo Patient
Report Date: 15/06/2026

Laboratory Results

HbA1c: 8.2 %
""",
    # AI follow-through demo (scores are the real pubmedbert values at
    # the calibrated thresholds; see docs/AI_DEMO.md):
    #   PSA -> "Prostate Specific Antigen"   SUGGESTED (0.69, no shared word)
    #   vitamin D -> "Vitamin D (25-OH)"     SUGGESTED (0.86); Vitamin B12 trap (0.67) rejected
    #   thyroid function -> TSH              AI_ABSTAINED (0.645 < 0.68): loop stays open
    #   kidney function -> Creatinine        RULE match (keyword table)
    #   "Review in 4 weeks"                  names no test: stays open
    FOLLOWTHROUGH_PLAN: f"""{SYNTHETIC_BANNER}

JEEVAFLOW DEMO CLINIC - FOLLOW-UP PLAN

Dr. Example Physician
Reg. No: SYN-12345
Report Date: 05/10/2026

Advice
Repeat PSA after 2 months.
Check vitamin D levels after 3 months.
Check thyroid function after 6 weeks.
Repeat kidney function test in 3 months.
Review in 4 weeks.
""",
    FOLLOWTHROUGH_LABS: f"""{SYNTHETIC_BANNER}

JEEVAFLOW DEMO LABORATORY RESULT

Report Date: 28/12/2026

Laboratory Results

Prostate Specific Antigen: 1.2 ng/mL
Vitamin D (25-OH): 31 ng/mL
Vitamin B12: 410 pg/mL
TSH: 3.2 mIU/L
Serum Creatinine: 1.1 mg/dL
""",
}


def demo_document_bytes(name: str) -> bytes:
    """
    Build a synthetic PDF deterministically (fixed metadata,
    no random file ID).
    """

    text = DEMO_DOCUMENTS[name]

    document = pymupdf.open()

    try:
        page = document.new_page()

        page.insert_text(
            (72, 72),
            text,
            fontsize=12,
        )

        document.set_metadata(
            {
                "title": name,
                "author": "JeevaFlow synthetic demo",
                "subject": SYNTHETIC_BANNER,
            }
        )

        return document.tobytes(
            garbage=3,
            deflate=True,
            no_new_id=True,
        )

    finally:
        document.close()


def write_demo_files(directory: Path = DEMO_DATA_DIR) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)

    paths = []

    for name in DEMO_DOCUMENTS:
        path = directory / name
        content = demo_document_bytes(name)

        if not path.exists() or path.read_bytes() != content:
            path.write_bytes(content)

        paths.append(path)

    return paths


def create_demo_document() -> str:
    """
    Backward-compatible helper: path to the initial demo report.
    """

    write_demo_files()

    return str(DEMO_DATA_DIR / INITIAL_REPORT)


def reset_patient_records(db: Session, patient_id: int) -> dict:
    """
    Crypto-shred every document of the (synthetic) demo patient and
    remove its consents, transactions and message logs, so the demo
    can be replayed. The audit trail is append-only and is kept.
    """

    from .pipeline import delete_document

    documents = db.query(Document).filter(Document.patient_id == patient_id).all()

    for document in documents:
        delete_document(db, document, "SYSTEM", "demo-reset", "DEMO_RESET")

    counts = {
        "documents": len(documents),
        "transactions": db.query(Transaction).filter(Transaction.patient_id == patient_id).delete(synchronize_session=False),
        "consents": db.query(Consent).filter(Consent.patient_id == patient_id).delete(synchronize_session=False),
        "whatsapp_messages": db.query(WhatsAppMessage).filter(WhatsAppMessage.patient_id == patient_id).delete(synchronize_session=False),
        "outbound_messages": db.query(OutboundMessage).filter(OutboundMessage.patient_id == patient_id).delete(synchronize_session=False),
    }

    db.query(EvidenceToken).filter(EvidenceToken.patient_id == patient_id).delete(synchronize_session=False)

    from .models import AIDecision

    counts["ai_decisions"] = db.query(AIDecision).filter(AIDecision.patient_id == patient_id).delete(
        synchronize_session=False
    )
    db.commit()

    return counts
